language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: '4'
    - node_js: '6'
    - node_js: '8'
script: "npm run-script test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
